name: Create docker image

on:
  push:
    branch: test

jobs:
  docker:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      IMAGE_NAME: naisplater
      YQ_VERSION: 3.3.2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # - name: Install gotpl
    #   run: |
    #     go get github.com/tsg/gotpl
    # - name: Install yq
    #   run: |
    #     mkdir -p $HOME/bin
    #     curl -Ls https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 -o $HOME/bin/yq && \
    #     chmod +x $HOME/bin/yq
    # - name: Set path
    #   run: |
    #     echo "PATH=/home/runner/go/bin:$HOME/bin:$PATH" >> $GITHUB_ENV
    - name: Bump version
      run: |
        make bump
    - name: Build docker image
      run: |
        make build
    - name: Run test
      run: |
        make docker-test
