name: Create docker image

on:
  push:
    branch: master
    paths:
      - naisplater
      - Makefile
      - Dockerfile
      - '.github/workflows/**'
      - 'test/**'

jobs:
  docker:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      IMAGE_NAME: naisplater
      GITHUB_OWNER: nais
      YQ_VERSION: 3.3.2
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Bump version
      run: |
        make bump
    - name: Build docker image
      run: |
        make build
    - name: Run test
      run: |
        make docker-test
    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.NAIS_ORG_GHCR_USERNAME }}
        password: ${{ secrets.NAIS_ORG_GHCR_TOKEN }}
    - name: Push Docker image
      run: |
        make push
    - name: Push updated version
      run: |
        git config --local user.email "TODO@todo.nais.io"
        git config --local user.name "Github naisplater action"
        git add version
        git commit -m "ci/cd: pipeline update to version $(cat version)"
        git push
