name: Create docker image

on:
  push:
    branch: test

jobs:
  docker:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      IMAGE_NAME: naisplater
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install gotpl
      run: |
        go get github.com/tsg/gotpl
    - name: Set path
      run: |
        echo "PATH=/home/runner/go/bin:$PATH" >> $GITHUB_ENV
    - name: Run test
      run: |
        make test
