name: Create docker image

on:
  push:
    branch: test
    paths-ignore:
      - version

jobs:
  docker:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      IMAGE_NAME: naisplater
      YQ_VERSION: 3.3.2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Bump version
      run: |
        make bump
    - name: Build docker image
      run: |
        make build
    - name: Run test
      run: |
        make docker-test
    - name: Login GPR
      run: |
        docker login -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN} docker.pkg.github.com
    - name: Push Docker image
      run: |
        make push
    - name: Push updated version
      run: |
        git config --local user.email "TODO@todo.nais.io"
        git config --local user.name "Github naisplater action"
        git add version
        git commit -m "ci/cd: pipeline update to version $(cat version)"
        git push
